//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cont_employee
    {
        public string IDcard { get; set; }
        public string Pno { get; set; }
        public string Name { get; set; }
        public string Birthday { get; set; }
        public string Sex { get; set; }
        public string Bank { get; set; }
        public string Account { get; set; }
        public string Tel { get; set; }
        public string Mobilephone { get; set; }
        public string Email { get; set; }
        public string Education { get; set; }
        public string Subsidy { get; set; }
        public string Aborigine { get; set; }
        public string Retired { get; set; }
        public string Foreignmk { get; set; }
        public string Nationality { get; set; }
        public string Password { get; set; }
        public string Note { get; set; }
        public string CIDCard { get; set; }
        public string UDateTime { get; set; }
        public int Taxrate { get; set; }
        public int CPensionRate { get; set; }
        public int Annbouns { get; set; }
        public int Annbouns_month { get; set; }
        public int Annbouns_salary { get; set; }
        public string AddressZipId { get; set; }
        public string AddressZipText { get; set; }
        public string Address { get; set; }
        public string AddressRegZipId { get; set; }
        public string AddressRegZipText { get; set; }
        public string AddressReg { get; set; }
    }
}
