//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outgoing_Stu
    {
        public string StudentNo { get; set; }
        public string ApplyType { get; set; }
        public string StudentName { get; set; }
        public string StudentEngName { get; set; }
        public string ApplyDepartment { get; set; }
        public string EduCode { get; set; }
        public string PassWord { get; set; }
        public string PassPortNo { get; set; }
        public string Country { get; set; }
        public string Sex { get; set; }
        public string Birthday { get; set; }
        public string Period { get; set; }
        public string Grade { get; set; }
        public string NowTel { get; set; }
        public string AlwaysAdd { get; set; }
        public string NowAdd { get; set; }
        public string TaiwanTel { get; set; }
        public string Email { get; set; }
        public string OSchool { get; set; }
        public string ODepartment { get; set; }
        public string SemesterS { get; set; }
        public string SemesterE { get; set; }
        public string ExitDate { get; set; }
        public string NonRegister { get; set; }
        public string Liaison_Name { get; set; }
        public string Liaison_Relation { get; set; }
        public string Liaison_Tel { get; set; }
        public string Liaison_Email { get; set; }
        public string Note1 { get; set; }
        public string Note2 { get; set; }
        public string Note3 { get; set; }
        public string OriPassWord { get; set; }
        public string CIDCard { get; set; }
        public string CreateDateTime { get; set; }
    }
}
