//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sch_Organ
    {
        public string UnitName { get; set; }
        public string UnitEngName { get; set; }
        public string UnitShort { get; set; }
        public string UnitEngShort { get; set; }
        public string UnitCode { get; set; }
        public string ManagerName { get; set; }
        public string UnitWWW { get; set; }
        public string UnitEmail { get; set; }
        public string UnitTel { get; set; }
        public string UnitFax { get; set; }
        public string Level1Unit { get; set; }
        public string Level2Unit { get; set; }
        public string SchLocal { get; set; }
        public string CreateDateTime { get; set; }
        public string CIDCard { get; set; }
        public string Note { get; set; }
        public string ManagerTitle { get; set; }
        public string Other_mark { get; set; }
        public string AccountingCode { get; set; }
    }
}
