//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stu_Status
    {
        public string StudentNo { get; set; }
        public string Semester { get; set; }
        public string CreateDateTime { get; set; }
        public string CIDCard { get; set; }
        public string StudentName { get; set; }
        public string StudentEngName { get; set; }
        public string IDCard { get; set; }
        public string BornLoc { get; set; }
        public string Birthday { get; set; }
        public string EduCode { get; set; }
        public string Ch_EduCode { get; set; }
        public string NowCondition { get; set; }
        public string RegisterLoc { get; set; }
        public string Sex { get; set; }
        public string AlwaysTel { get; set; }
        public string AlwaysAddress { get; set; }
        public string NowTel { get; set; }
        public string NowAddress { get; set; }
        public string MobilePhone { get; set; }
        public string StudentSource { get; set; }
        public string EnterDate { get; set; }
        public string EnterCode { get; set; }
        public string AbroadMark { get; set; }
        public string IndigenousMark { get; set; }
        public string MaimedMark { get; set; }
        public string ForeignerMark { get; set; }
        public string OtherMark { get; set; }
        public string OutsideMark { get; set; }
        public string Studyperiod { get; set; }
        public string ParentsName { get; set; }
        public string ParentsYear { get; set; }
        public string ParentsOccupation { get; set; }
        public string ParentsRebtion { get; set; }
        public string ParentsAddress { get; set; }
        public string ParentsTel { get; set; }
        public string Account { get; set; }
        public string StudyMark { get; set; }
        public string Note { get; set; }
        public string Password { get; set; }
        public string Now_Level { get; set; }
        public string StopMark { get; set; }
        public string OutEmail { get; set; }
        public string NewStu_Mark { get; set; }
        public string BloodType { get; set; }
        public string RegisterAddress { get; set; }
        public string GeneralMark { get; set; }
        public string MongoTibetanMark { get; set; }
        public string MotionMark { get; set; }
        public string ChangeDep_Mark { get; set; }
        public string TimeOf_Mark { get; set; }
        public string DoubleDegrees_Mark { get; set; }
        public string AssistDep_Mark { get; set; }
        public string AddscoreMark { get; set; }
        public string Addmark { get; set; }
        public string ChangeSch_Mark { get; set; }
        public string Duplex_Stu { get; set; }
        public string TaxSendMark { get; set; }
        public string TaxRegisterAddress { get; set; }
        public string Ori_EduCode { get; set; }
        public string edu_note { get; set; }
        public string DualDegree_Mark { get; set; }
        public string China_Mark { get; set; }
        public byte[] EryPwd { get; set; }
        public byte[] EryID { get; set; }
        public string C6C8_mark { get; set; }
        public string PDProtect_mark { get; set; }
        public string Auth_mark { get; set; }
        public string Alumni_Agree { get; set; }
        public bool VisitingRelativesMark { get; set; }
    }
}
