//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AD_Labor
    {
        public string Listno { get; set; }
        public string IDcard { get; set; }
        public string ADclass { get; set; }
        public string Statusno { get; set; }
        public string Studyno { get; set; }
        public string AccSource { get; set; }
        public string ListnoSrc { get; set; }
        public string GovInsu { get; set; }
        public string GInsuDesc { get; set; }
        public string SpecStatus { get; set; }
        public string Accno { get; set; }
        public string Leader { get; set; }
        public string SubLeader { get; set; }
        public Nullable<System.DateTime> Term_from { get; set; }
        public Nullable<System.DateTime> Term_end { get; set; }
        public Nullable<System.DateTime> QuitDate { get; set; }
        public int Salary { get; set; }
        public double YearEndMonth { get; set; }
        public int YearEndBonuses { get; set; }
        public int Pensionrate { get; set; }
        public string Department { get; set; }
        public int SelfLabor { get; set; }
        public int SelfPension { get; set; }
        public int SelfHealth { get; set; }
        public int EmpLabor { get; set; }
        public int EmpPension { get; set; }
        public int EmpHealth { get; set; }
        public Nullable<int> FamilyHealth { get; set; }
        public string Note { get; set; }
        public string CIDCard { get; set; }
        public string UDateTime { get; set; }
        public string ProjectName { get; set; }
        public int Bonus { get; set; }
        public string FamilyNum { get; set; }
    }
}
