//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AD_List
    {
        public string Listno { get; set; }
        public string Locked { get; set; }
        public string Confirmed { get; set; }
        public string Confirm_name { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public string ChangeFrom { get; set; }
        public Nullable<System.DateTime> StopDate { get; set; }
        public string Note { get; set; }
        public string CIDCard { get; set; }
        public string UDateTime { get; set; }
        public Nullable<System.DateTime> ExpirDate { get; set; }
        public string PerCheck_name { get; set; }
        public Nullable<System.DateTime> PerCheck_Date { get; set; }
        public string InsCheck_name { get; set; }
        public Nullable<System.DateTime> InsCheck_Date { get; set; }
        public string BasCheck_name { get; set; }
        public Nullable<System.DateTime> BasCheck_Date { get; set; }
    }
}
