//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_nowperson_w
    {
        public string unitname { get; set; }
        public string Name { get; set; }
        public string IDcard { get; set; }
        public string Password { get; set; }
        public string Birthday { get; set; }
        public string WorkTitle { get; set; }
        public string Term_start { get; set; }
        public string Term_end { get; set; }
        public Nullable<int> Worksno { get; set; }
        public string email2 { get; set; }
    }
}
