//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_schoolmember
    {
        public string Department { get; set; }
        public string Name { get; set; }
        public string IDCard { get; set; }
        public string Address { get; set; }
        public string IDstatus { get; set; }
        public string Tel { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public string BankNo { get; set; }
        public string Account { get; set; }
        public string Note { get; set; }
        public string PB_Mark { get; set; }
        public string CIDCard { get; set; }
        public string UDDateTime { get; set; }
        public string jobtitle { get; set; }
        public string rank { get; set; }
        public string nowcondition { get; set; }
        public string cardno { get; set; }
    }
}
